### ISSUE TITLE
Wrong text in the Cancel button

### ISSUE THREAD

**Issue by hellomitesh** [HelpinOutMovement/helpinout-app-android#10]
On "Help requests received from" screen.  The bottom button should be "Cancel this Offer"  
(currently it shows "Cancel this Request."  This in not correct)

**Comment by AvneeshGupta1** [comment]
fixed

**Comment by hellomitesh** [comment]
This hasn't been fixed.  It still shows "Cancel this request" (this is wrong).  

It has to show, "Cancel this offer".
